version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      maven: 3.8
  build:
    commands:
      - echo "Building and packaging"
      - mvn install -DskipTests
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - target/SpringBootReactiveCRUD-0.0.1-SNAPSHOT.jar
