version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Building and packaging"
      - mvn install -DskipTests
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*.jar'
