---
- name: Download and Deploy Artifact
  hosts: webserver
  become: yes

  vars:
    - projectName: "SpringBootReactive"
    - app_name: springBootReactive
    - nexus_repository_url: 'http://nexus-lb-1617573302.ap-south-1.elb.amazonaws.com/#browse/browse:spring-boot-reactive'
    - nexus_username: 'admin'
    - nexus_password: 'admin'

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /opt/app
        state: directory

    - name: Download the artifact from Nexus
      community.general.maven_artifact:
        group_id: com.reactive
        artifact_id: "{{ projectName }}"
        repository_url: "{{ nexus_repository_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        dest: /opt/app/{{ app_name }}.jar
        ansible_python_interpreter: /usr/bin/python3

    - name: create service file
      template:
        src: jarFile.j2
        dest: /etc/systemd/system/springBoot-latest.service

    - name: start service
      service:
        name: springBoot-latest.service
        state: restarted
