---
- name: Download and Deploy Artifact
  hosts: webserver

  vars:
    - projectName: "SpringBootReactive"
    - app_name: springBootReactive
    - nexus_repository_url: 'http://65.2.78.134:8081/repository/spring-boot-reactive'
    - nexus_username: 'admin'
    - nexus_password: 'admin'
    - artifact_version:

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /opt/app
        state: directory

    - name: Download the artifact from Nexus
      community.general.maven_artifact:
        group_id: com.reactive
        artifact_id: "{{ projectName }}"
        version: "{{ artifact_version }}"
        repository_url: "{{ nexus_repository_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        dest: /tmp/{{ app_name }}.jar
      register: download_result

    - name: Copy the downloaded artifact to the web server
      ansible.builtin.copy:
        src: /tmp/{{ app_name }}.jar
        dest: /opt/app/{{ app_name }}.jar

    - name: create service file
      template:
        src: jarFile.j2
        dest: /etc/systemd/system/springBoot-latest.service

    - name: start service
      service:
        name: springBoot-latest.service
        state: restarted
