---
- name: Download and Deploy Artifact
  hosts: webserver
  become: yes

  vars:
    - projectName: "SpringBootReactive"
    - app_name: springBootReactive
    - nexus_repository_url: 'http://nexus-lb-1617573302.ap-south-1.elb.amazonaws.com/repository/spring-boot-reactive/'
    - nexus_username: 'admin'
    - nexus_password: 'admin'

  tasks:
    - name: create app directory if does not exist
      file:
        path: /opt/app
        state: directory

    - name: Download the artifact from Nexus
      maven_artifact:
        group_id: com.reactive
        artifact_id: "{{ projectName }}"
        repository_url: "{{ nexus_repository_url }}"
        version: 0.0.1-SNAPSHOT
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        dest: /opt/app/{{ app_name }}.jar

    - name: create service file
      template:
        src: jarFile.j2
        dest: /etc/systemd/system/springBoot-latest.service

    - name: Reload systemd manager
      ansible.builtin.systemd:
          daemon_reload: yes

    - name: Enable the service
      ansible.builtin.service:
        name: springBoot-latest
        enabled: yes

    - name: Start the service
      ansible.builtin.service:
        name: springBoot-latest
        state: started
